apiVersion: v1
kind: ReplicationController
metadata:
  name: helloworld-controller
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: k8s-course
        image: alzamabar/k8s-course:v1
        ports:
        - name: nodejs-port
          containerPort: 3000
