apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
  - name: k8s-course
    image: alzamabar/k8s-course:v2
    ports:
    - name: nodejs-port
      containerPort: 3000
